import React, { useState } from 'react';
import { SchematicComponent, Wire } from '../../types';
import { Network, Copy, Check, Download, X } from 'lucide-react';

interface NetlistPanelProps {
  components: SchematicComponent[];
  wires: Wire[];
  isOpen: boolean;
  onClose: () => void;
  circuitTitle: string;
}

export const NetlistPanel: React.FC<NetlistPanelProps> = ({
  components,
  wires,
  isOpen,
  onClose,
  circuitTitle,
}) => {
  const [copied, setCopied] = useState(false);
  if (!isOpen) return null;

  // Build netlist mapping: Net Name -> array of "R1.1", "U1.3", etc.
  const netMap = new Map<string, string[]>();

  for (const comp of components) {
    for (const pin of comp.pins) {
      if (pin.net) {
        const list = netMap.get(pin.net) || [];
        list.push(`${comp.designator}.${pin.id}`);
        netMap.set(pin.net, list);
      }
    }
  }

  // Generate SPICE .cir simulation netlist format
  const spiceLines: string[] = [
    `* SPICE Netlist for: ${circuitTitle}`,
    `* Generated by Electronic Schematic & Circuit Board Designer`,
    `* Date: ${new Date().toUTCString()}`,
    '',
  ];

  for (const comp of components) {
    const p1 = comp.pins[0]?.net || '0';
    const p2 = comp.pins[1]?.net || '0';
    const p3 = comp.pins[2]?.net || '0';

    if (comp.type === 'resistor') {
      spiceLines.push(`${comp.designator} ${p1} ${p2} ${comp.value.replace('Ω', '')}`);
    } else if (comp.type === 'capacitor' || comp.type === 'polarized_capacitor') {
      spiceLines.push(`${comp.designator} ${p1} ${p2} ${comp.value}`);
    } else if (comp.type === 'diode' || comp.type === 'led') {
      spiceLines.push(`${comp.designator} ${p1} ${p2} DMOD_${comp.value.replace(/\s+/g, '_')}`);
    } else if (comp.type === 'npn_bjt') {
      // Collector, Base, Emitter
      spiceLines.push(`Q_${comp.designator} ${p2} ${p1} ${p3} QMOD_NPN`);
    } else if (comp.type === 'vcc') {
      spiceLines.push(`V_${comp.designator} ${p1} 0 DC 5.0V`);
    } else if (comp.type === 'battery') {
      spiceLines.push(`V_${comp.designator} ${p1} ${p2} DC 9.0V`);
    } else {
      spiceLines.push(`X_${comp.designator} ${comp.pins.map((p) => p.net || '0').join(' ')} ${comp.value}`);
    }
  }

  spiceLines.push('');
  spiceLines.push('.model DMOD_1N4148 D (IS=2.52n RS=0.568 N=1.752 BV=100)');
  spiceLines.push('.model QMOD_NPN NPN (IS=1e-14 BF=100 VAF=100)');
  spiceLines.push('.tran 1u 10m');
  spiceLines.push('.end');

  const spiceText = spiceLines.join('\n');

  const handleCopy = () => {
    navigator.clipboard.writeText(spiceText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([spiceText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${circuitTitle.toLowerCase().replace(/\s+/g, '_')}.cir`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-xs p-4">
      <div className="relative w-full max-w-3xl max-h-[85vh] flex flex-col bg-slate-900 border border-slate-700 rounded-xl shadow-2xl overflow-hidden text-slate-100 font-sans">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/90">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-purple-500/20 text-purple-400 rounded-lg border border-purple-500/30">
              <Network className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
                Netlist &amp; SPICE Export
                <span className="text-xs px-2 py-0.5 bg-purple-950 text-purple-300 border border-purple-800 rounded font-mono">
                  {netMap.size} Electrical Nets
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Pin node associations and standard SPICE netlist syntax (.cir)
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          {/* Net Connections List */}
          <div>
            <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
              Schematic Net Graph
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {Array.from(netMap.entries()).map(([netName, pins]) => (
                <div
                  key={netName}
                  className="p-2.5 bg-slate-950/80 rounded-lg border border-slate-800 text-xs font-mono"
                >
                  <div className="font-bold text-sky-400 mb-1 flex items-center justify-between">
                    <span>{netName}</span>
                    <span className="text-[10px] text-slate-500 font-normal">
                      {pins.length} pins
                    </span>
                  </div>
                  <div className="text-[11px] text-slate-300">
                    {pins.join(', ')}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SPICE Netlist Code Box */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">
                SPICE Simulation Netlist (.cir)
              </h3>
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleCopy}
                  className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded text-xs flex items-center gap-1 font-mono transition-colors"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button
                  onClick={handleDownload}
                  className="px-2.5 py-1 bg-purple-600 hover:bg-purple-500 text-white rounded text-xs flex items-center gap-1 font-mono transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download .cir
                </button>
              </div>
            </div>
            <pre className="p-4 bg-slate-950 rounded-lg border border-slate-800 text-[11px] text-purple-300 font-mono overflow-x-auto leading-relaxed max-h-56">
              {spiceText}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end px-6 py-4 border-t border-slate-800 bg-slate-900/90">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
